export interface LandingsCourse {
  name: string
  location: string
  holes: HoleData[]
}

export interface HoleData {
  hole_number: number
  par: number
  yardage: number
}

export const LANDINGS_COURSES: LandingsCourse[] = [
  {
    name: 'Palmetto',
    location: 'The Landings, Savannah, GA',
    holes: [
      { hole_number: 1, par: 4, yardage: 394 },
      { hole_number: 2, par: 5, yardage: 535 },
      { hole_number: 3, par: 3, yardage: 203 },
      { hole_number: 4, par: 4, yardage: 485 },
      { hole_number: 5, par: 3, yardage: 198 },
      { hole_number: 6, par: 4, yardage: 453 },
      { hole_number: 7, par: 5, yardage: 531 },
      { hole_number: 8, par: 4, yardage: 343 },
      { hole_number: 9, par: 4, yardage: 406 },
      { hole_number: 10, par: 5, yardage: 530 },
      { hole_number: 11, par: 4, yardage: 412 },
      { hole_number: 12, par: 3, yardage: 187 },
      { hole_number: 13, par: 4, yardage: 392 },
      { hole_number: 14, par: 5, yardage: 495 },
      { hole_number: 15, par: 3, yardage: 165 },
      { hole_number: 16, par: 4, yardage: 456 },
      { hole_number: 17, par: 4, yardage: 434 },
      { hole_number: 18, par: 4, yardage: 426 },
    ],
  },
  {
    name: 'Marshwood',
    location: 'The Landings, Savannah, GA',
    holes: [
      { hole_number: 1, par: 4, yardage: 431 },
      { hole_number: 2, par: 5, yardage: 551 },
      { hole_number: 3, par: 4, yardage: 395 },
      { hole_number: 4, par: 3, yardage: 203 },
      { hole_number: 5, par: 5, yardage: 567 },
      { hole_number: 6, par: 4, yardage: 346 },
      { hole_number: 7, par: 4, yardage: 384 },
      { hole_number: 8, par: 3, yardage: 209 },
      { hole_number: 9, par: 4, yardage: 449 },
      { hole_number: 10, par: 4, yardage: 425 },
      { hole_number: 11, par: 4, yardage: 451 },
      { hole_number: 12, par: 3, yardage: 177 },
      { hole_number: 13, par: 5, yardage: 504 },
      { hole_number: 14, par: 4, yardage: 383 },
      { hole_number: 15, par: 5, yardage: 521 },
      { hole_number: 16, par: 3, yardage: 163 },
      { hole_number: 17, par: 4, yardage: 334 },
      { hole_number: 18, par: 4, yardage: 411 },
    ],
  },
  {
    name: 'Magnolia',
    location: 'The Landings, Savannah, GA',
    holes: [
      { hole_number: 1, par: 4, yardage: 344 },
      { hole_number: 2, par: 5, yardage: 561 },
      { hole_number: 3, par: 3, yardage: 154 },
      { hole_number: 4, par: 4, yardage: 405 },
      { hole_number: 5, par: 4, yardage: 381 },
      { hole_number: 6, par: 5, yardage: 486 },
      { hole_number: 7, par: 4, yardage: 399 },
      { hole_number: 8, par: 3, yardage: 185 },
      { hole_number: 9, par: 4, yardage: 433 },
      { hole_number: 10, par: 4, yardage: 395 },
      { hole_number: 11, par: 5, yardage: 555 },
      { hole_number: 12, par: 4, yardage: 439 },
      { hole_number: 13, par: 4, yardage: 423 },
      { hole_number: 14, par: 3, yardage: 172 },
      { hole_number: 15, par: 4, yardage: 382 },
      { hole_number: 16, par: 5, yardage: 544 },
      { hole_number: 17, par: 3, yardage: 219 },
      { hole_number: 18, par: 4, yardage: 418 },
    ],
  },
  {
    name: 'Deer Creek',
    location: 'The Landings, Savannah, GA',
    holes: [
      { hole_number: 1, par: 4, yardage: 396 },
      { hole_number: 2, par: 3, yardage: 189 },
      { hole_number: 3, par: 5, yardage: 551 },
      { hole_number: 4, par: 4, yardage: 385 },
      { hole_number: 5, par: 4, yardage: 320 },
      { hole_number: 6, par: 5, yardage: 580 },
      { hole_number: 7, par: 4, yardage: 396 },
      { hole_number: 8, par: 3, yardage: 201 },
      { hole_number: 9, par: 4, yardage: 480 },
      { hole_number: 10, par: 4, yardage: 449 },
      { hole_number: 11, par: 4, yardage: 388 },
      { hole_number: 12, par: 3, yardage: 188 },
      { hole_number: 13, par: 4, yardage: 443 },
      { hole_number: 14, par: 5, yardage: 582 },
      { hole_number: 15, par: 4, yardage: 442 },
      { hole_number: 16, par: 4, yardage: 405 },
      { hole_number: 17, par: 3, yardage: 197 },
      { hole_number: 18, par: 5, yardage: 593 },
    ],
  },
  {
    name: 'Terrapin',
    location: 'The Landings, Savannah, GA',
    holes: [
      { hole_number: 1, par: 4, yardage: 425 },
      { hole_number: 2, par: 4, yardage: 403 },
      { hole_number: 3, par: 3, yardage: 149 },
      { hole_number: 4, par: 4, yardage: 405 },
      { hole_number: 5, par: 5, yardage: 518 },
      { hole_number: 6, par: 4, yardage: 409 },
      { hole_number: 7, par: 4, yardage: 406 },
      { hole_number: 8, par: 3, yardage: 192 },
      { hole_number: 9, par: 5, yardage: 504 },
      { hole_number: 10, par: 4, yardage: 345 },
      { hole_number: 11, par: 4, yardage: 394 },
      { hole_number: 12, par: 3, yardage: 200 },
      { hole_number: 13, par: 4, yardage: 452 },
      { hole_number: 14, par: 5, yardage: 547 },
      { hole_number: 15, par: 4, yardage: 381 },
      { hole_number: 16, par: 4, yardage: 411 },
      { hole_number: 17, par: 3, yardage: 184 },
      { hole_number: 18, par: 5, yardage: 512 },
    ],
  },
  {
    name: 'Oakridge',
    location: 'The Landings, Savannah, GA',
    holes: [
      { hole_number: 1, par: 4, yardage: 415 },
      { hole_number: 2, par: 4, yardage: 441 },
      { hole_number: 3, par: 3, yardage: 186 },
      { hole_number: 4, par: 5, yardage: 519 },
      { hole_number: 5, par: 3, yardage: 200 },
      { hole_number: 6, par: 4, yardage: 354 },
      { hole_number: 7, par: 5, yardage: 501 },
      { hole_number: 8, par: 4, yardage: 337 },
      { hole_number: 9, par: 4, yardage: 378 },
      { hole_number: 10, par: 4, yardage: 435 },
      { hole_number: 11, par: 4, yardage: 406 },
      { hole_number: 12, par: 3, yardage: 176 },
      { hole_number: 13, par: 5, yardage: 505 },
      { hole_number: 14, par: 4, yardage: 338 },
      { hole_number: 15, par: 5, yardage: 476 },
      { hole_number: 16, par: 3, yardage: 140 },
      { hole_number: 17, par: 4, yardage: 405 },
      { hole_number: 18, par: 4, yardage: 391 },
    ],
  },
]
